### ISSUE TITLE
can you share the idea on how to do this in gitlab?

### ISSUE THREAD

**Issue by ozbillwang** [anothrNick/github-tag-action#164]
I'd like to use this code to manage the tag and releases. But my company's git codes are based on Gitlab. 

My understanding is, if this action can be run in docker, I can run in any place, right?

So any idea if I want to integrate it in Gitlab ci pipeline?

In another word, how can I run this action with `docker run` command?

**Comment by sammcj** [comment]
Hey @ozbillwang, this action is designed for use with Github Actions, however if you were to build an image from the Dockerfile in this repo and store it wherever you store your other container images you should be able to reference said image instead of this Action, as you're using GitLab you may need to add some environment variables that are only present in Github Actions.

**Comment by ozbillwang** [comment]
thanks, in fact, I did it already, for generic usage.

https://github.com/alpine-docker/git-tag/tree/re-do

it is only used to generate next tagName, but will not update and release tag (git push --tags), because I don't know this tool will be used in gitlab, github, bitbucket, etc.
