### ISSUE TITLE
Feature Request: Allow Release Branch Suffix like Prerelease Suffix

### ISSUE THREAD

**Issue by Meywether** [anothrNick/github-tag-action#248]
Hiho :)
Thanks for the great repository and your work. 
Do you think it is possible to allow a release suffix based on the current branchname like in die property prerelease suffix?

![image](https://user-images.githubusercontent.com/39849054/217468894-9fc4424b-ae86-4fce-8d90-bf9f939abf75.png)

Thank you in advance :)

Kind regards
Meywether

**Comment by sbe-arg** [comment]
Ill try to do this in the next week or so... Cc @sammcj

**Comment by Meywether** [comment]
@sbe-arg You are my hero :) thank you :)

**Comment by sbe-arg** [comment]
hey @Meywether we had a few bugs in the last release that delayed this but I haven't forgotten about it.

**Comment by Meywether** [comment]
Hey, @sbe-arg  thank you very much for your update :) 
Do not worry, thank you very much :)

**Comment by sbe-arg** [comment]
Is still happening been delayed testing this properly and sorting other bugs... don't loose hope XD

**Comment by sbe-arg** [comment]
Noticed also relates to #208

**Comment by sbe-arg** [comment]
Hey @Meywether after a few days of testing and playing with scenarios for this.
I don't really believe is a good solution to create suffixed tags for non pre-releases.

The main explanation is that people might use this for branching products like vX.X.X-someapp.0,  vX.X.Z-someotherapp.0, this will read to multiple tag nightmares in the repositories.

If this is your use case you can probably go with packing your artifacts instead of packing your apps with repo tags.
In a version x.x.x multiple sub version apps can be created and pushed to github packages.

The semversioning of the apps can be created using this action in dryrun mode and using the output as source of the package creations. 

I'm closing this issue for now.
