### ISSUE TITLE
#major #patch tag in commit body has no effect

### ISSUE THREAD

**Issue by tamoore** [anothrNick/github-tag-action#53]
I tried adding `#major` and `#patch` tags to the body of my commit message for version `1.13.0` but it still released a minor version.

My env vars were:

```          
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
WITH_V: true
DRY_RUN: true
```

**Comment by anothrNick** [comment]
Make sure you are pulling down multiple commits with your source:

```
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
```

The last commit is probably the merge commit, which wouldn't include the commit with your message to specify the bump.

**Comment by gshade** [comment]
I'm running into the same issue. While including `#major` or `#patch` into the commit "title" (first line) works correctly, including them in the commit "body" (subsequent lines) does nothing and it instead falls back to `DEFAULT_BUMP`.

I'm pretty sure the issue here is that `git log --pretty=oneline` only includes the commit title, and not the full commit message with commit body.
